name    'vorlock-fetchmail'
version '0.1.0'
source  'https://github.com/BashtonLtd/puppet-fetchmail'
author  'Marcin Kulisz'
license 'Apache License 2.0'
summary 'Fetchmail Module'
description  'fetchmail module for puppet'
project_page 'https://github.com/BashtonLtd/puppet-fetchmail'
